name: petadopt
description: Proyecto de Flutter.
environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2

  # Supabase
  supabase_flutter: ^2.0.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  #injectable: ^2.3.2
  
  # Navigation
  go_router: ^13.0.0
  
  # Network
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # Gemini AI
  google_generative_ai: ^0.2.1
  
  # Image Handling
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  
  # UI
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  
  # Deep Links
  app_links: ^6.2.0

flutter:
  uses-material-design: true
  assets:
  - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  #injectable_generator: ^2.4.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  
  # Linting
  flutter_lints: ^3.0.0

dependency_overrides:
  app_links: 6.2.0